name: WorldGuardTitle
version: 2.0
main: me.droreo002.wtitle.WorldGuardTitle
depend: [WorldGuard, OreoCore]
authors: [DrOreo002]
description: World guard title plugin

commands:
  worldguardtitle:
    aliases: [wtitle, wtl, wt, wgt]
permission:
  wtitle.admin:
    default: op
